name: dmnseq
channels:
  - conda-forge
  - bioconda
channel_priority: strict
dependencies:
  - python=3.10
  - pip
  - mamba
  - snakemake-minimal=7.32.4
  - samtools=1.15.1
  - htslib=1.18
  - hisat2=2.2.1
  - subread=2.0.6
  - pysam=0.21.0
  - biopython=1.83
  - deeptools=3.5.5
  
  - pip:
    - cutadapt==4.6
    - multiqc